run:
  timeout: 5m
  tests: false
issues:
  exclude-rules:
    - path: 'cmd/memory.go'
      linters:
        - funlen
        - gocognit
        - gocyclo
        - maintidx
    - path: 'cmd/filesystem.go'
      linters:
        - funlen
        - gocognit
        - maintidx
        - gocyclo
    - path: 'cmd/psi.go'
      linters:
        - funlen
        - gocognit
        - gocyclo
        - maintidx
    - path: 'internal/sensors/sensors.go'
      linters:
        - funlen
        - gocognit
    - path: 'internal/filesystem/filesystem.go'
      linters:
        - funlen
        - gocognit
        - gocyclo
        - maintidx
    - path: 'cmd/filesystem.go'
      linters:
        - nestif
    - path: 'internal/netdev/netdev.go'
      linters:
        - deadcode
        - golint
        - unused
        - nosnakecase
        - stylecheck
        - varcheck
        - revive
linters:
   enable-all: true
   disable:
     - mnd
     - dupl
     - cyclop
     - depguard
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - godot
     - err113
     - gofumpt
     - gomnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
