version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - lll
    - mnd
    - musttag
    - nakedret
    - nlreturn
    - nolintlint
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - maintidx
        path: cmd/memory.go
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - maintidx
        path: cmd/filesystem.go
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - maintidx
        path: cmd/psi.go
      - linters:
          - funlen
          - gocognit
        path: internal/sensors/sensors.go
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - maintidx
        path: internal/filesystem/filesystem.go
      - linters:
          - nestif
        path: cmd/filesystem.go
      - linters:
          - deadcode
          - golint
          - nosnakecase
          - revive
          - staticcheck
          - unused
          - varcheck
        path: internal/netdev/netdev.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
