# See documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod download

release:
  github:
  draft: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - arm64
      - amd64
      - 386
      - riscv64
    ldflags:
      - -X github.com/NETWAYS/check_system_basics/cmd.version={{.Version}}
